% Testing cases for eeg_pac function.
% Useful guide for the use of different combinations and methods in the
% toolbox
%
% Author:  Ramon Martinez Cancino SCCN/INC, UCSD 2018
%
% Copyright (C) 2018 Martinez Cancino, INC, SCCN
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

%% Parameters

% Signal parameters
fc            = 60;   % Frequency of the carrier wave. Recommended: [60]
fm            = 8;    % Frequency of the modulating wave. Recommended: [60]
max_time      = 7;    % Time of the simulation. Recommended: single trial [6], multiple trials [2]
n_trials      = 200;  % Number of trials. Recommended: single trial [1], multiple trials [1000]
s_rate        = 500;  % Sampling rate. Recommended: single trial [500], multiple trials [250]
padtime       = 0;    % Padding time at the start and end of the signal. 
snrval        = 10;   % Signal to noise ratio. Recommended: [5]
maxshift      = 10;   % Maximum shifts (jitter) injected into the data. Recommended: single trial [1], multiple trials [10]
nsegm         = 5;    % Number of segments in the data. Each segment is a block with our without modulation


% Method parameters                      
nfreqsphase = 3;       % Number of frequencies used for the phase. Recommended: [10]
nfreqsamp   = 2;       % Number of frequencies used for the amplitude. Recommended: [10]
alpha       = 0.05;    % Alpha value used for statistics. If alpha = [] the statistics are not computed.
                       % Recommended: [0.05] (or [] for less computationtime)
compute_mvl = true;    % Compute the Mean Vector Length Modulation Index
compute_kl  = true;    % Compute the Kullback Leibler Modulation Index
compute_glm = true;    % Compute the GLM Modulation Index
phaserange  = 8;       % Range of phases to be used
                       % Recommended: [4 25]
amprange    = 60;      % Range of amplitudes to be used  Recommended: [30 100]
nsurrogate  = 10;      % Number of surrogates. Recommended: [200].
nbinskl     = 18;      % Number of bins for the Kullback Leibler Modulation
                       % index. Recommended: [8]

% Do not modify the code beyond this point
%% Generate 1D data
tlimits      = [0 max_time];
plot_flag    = 1;
[data_singletrial,t_outtmp]  = cfctool_simpac(fc,fm,tlimits,'Ac',5,'Am',1,'fs',s_rate,'cpfunc','block','blockamp',1, 'nsegm',nsegm,'plot_flag', plot_flag,'padtime',padtime,'snr',snrval,'m',1);

%% INSTMIPAC (no surr)
mipacvarthreshval =0.002;
[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method', 'instmipac',...
                                                         'freqs',          phaserange ,...
                                                         'nfreqs1',        nfreqsphase,...
                                                         'nfreqs2',        nfreqsamp,...
                                                         'freqs2',         amprange,...
                                                         'winsize',        s_rate,...
                                                         'nboot',          nsurrogate,...
                                                         'butterorder',    6, ...
                                                         'mipacvarthresh', mipacvarthreshval,...
                                                         'timefreq',       1,...
                                                         'ntimesout',      length(data_singletrial));
                                                     
%% MVLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% GLM (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method',    'glm',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% KLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method', 'klmi',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% INSTMIPAC (surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method', 'instmipac',...
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% MVLMI (surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method', 'mvlmi',...
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% GLM (surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method', 'glm',...
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% KLMI (surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'method',   'klmi',...
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', length(data_singletrial));
%% Generate 2D data
clear data_pac
max_time      = 2;            % Time of the simulation. Recommended: single trial [6], multiple trials [2]
nfreqsphase   = 1;
nfreqsamp     = 1;

tlimits = [-1 max_time];
s_rate  = 100; 
snrval  = 10;     
s = randi(maxshift, n_trials,1);

for i=1:n_trials
     plot_flag = i == 1;
     [datatmp,t_outtmp]  = cfctool_simpac(fc,fm,tlimits,'Ac',5,'Am',1,'fs',s_rate,'cpfunc','block','blockamp',1, 'nsegm',nsegm,'plot_flag', plot_flag,'padtime',padtime,'snr',snrval,'m',1);
     datatmp = [datatmp(s(i):end) datatmp(1:s(i)-1)];
     data_pac(1,:,i) = [datatmp(end-ceil(maxshift/2):end) datatmp(1:end-ceil(maxshift/2)-1)]; 
end

%%  MVLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                         
                                                         'winsize',   s_rate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', size(data_pac,2));
%%   MVLMI (w surr)           

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'mvlmi',...
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...                                                         
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                      
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1,...
                                                         'ntimesout', size(data_pac,2));
%% KLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'klmi',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                         
                                                         'winsize',   s_rate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', size(data_pac,2));
%%   KLMI (w surr)           

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'klmi',...
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...                                                         
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                      
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1,...
                                                         'ntimesout', size(data_pac,2));
%% GLMmi (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'glm',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                         
                                                         'winsize',   s_rate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', size(data_pac,2));
%%    GLMmi (w surr)          

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'glm',...                                                       
                                                         'alpha',     alpha ,...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                      
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1,...
                                                         'ntimesout', size(data_pac,2));
 %% ERMIPAC (no surr)
 
 [pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'ermipac',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                      
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1,...
                                                         'ntimesout', size(data_pac,2));
  %% ERMIPAC (w surr)
 
 [pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'ermipac',...
                                                         'alpha',     alpha,... 
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                      
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1,...
                                                         'ntimesout', size(data_pac,2));    
%%
%% Compute PAC multiple freqs

max_time      = 2;            % Time of the simulation.
phaserange    = [8 712];
amprange      = [60 70];
nfreqsphase   = 3;
nfreqsamp     = 3;

%%  MVLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'method', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'freqs2',    amprange,...
                                                         'nfreqs2',   nfreqsamp,...                                                         
                                                         'winsize',   s_rate,...
                                                         'timefreq',  1,...
                                                         'ntimesout', size(data_pac,2));

