% Testing cases
%
%
% Author:  Ramon Martinez Cancino SCCN/INC, UCSD 2018
%
% Copyright (C) 2018 Martinez Cancino, INC, SCCN
%
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

%% Parameters

% Signal parameters
fc            = 60;   % Frequency of the carrier wave. Recommended: [60]
fm            = 8;    % Frequency of the modulating wave. Recommended: [60]
max_time      = 7;    % Time of the simulation. Recommended: single trial [6], multiple trials [2]
n_trials      = 30;    % Number of trials. Recommended: single trial [1], multiple trials [1000]
s_rate        = 500;  % Sampling rate. Recommended: single trial [500], multiple trials [250]
padtime       = 0;    % Padding time at the start and end of the signal. 
                      % Should increase with sampling size.
                      % Recommended: 0.5
snrval        = 10;    % Signal to noise ratio. Recommended: [5]
maxshift      = 10;   % Maximum shifts (jitter) injected into the data.Recommended: single trial [1], multiple trials [10]
nsegm         = 5;    % Number of segments in the data. Each segment is a block with our without modulation


% Method parameters                      
nfreqsphase = 3;       % Number of frequencies used for the phase. Recommended: [10]
nfreqsamp   = 2;        % Number of frequencies used for the amplitude. Recommended: [10]
alpha       = [];       % Alpha value used for statistics. If alpha = [] the statistics are not computed.
                        % Recommended: [0.05] (or [] for less computationtime)
compute_mvl = true;     % Compute the Mean Vector Length Modulation Index
compute_kl  = true;     % Compute the Kullback Leibler Modulation Index
compute_glm = true;     % Compute the GLM Modulation Index
phaserange  = 8;        % Range of phases to be used
                        % Recommended: [4 25]
amprange    = 60;       % Range of amplitudes to be used  Recommended: [30 100]
nsurrogate  = 200;      % Number of surrogates. Recommended: [200].
nbinskl     = 18;       % Number of bins for the Kullback Leibler Modulation
                        % index. Recommended: [8]

% Do not modify the code beyond this point
%% Generate 1D data
tlimits      = [0 max_time];
plot_flag    = 1;
[data_singletrial,t_outtmp]  = generate_pac_signal(fc,fm,tlimits,'Ac',5,'Am',1,'fs',s_rate,'cpfunc','block','blockamp',1, 'nsegm',nsegm,'plot_flag', plot_flag,'padtime',padtime,'snr',snrval,'m',1);

%% INSTMIPAC
mipacvarthreshval =0.002;
[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'instmipac',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  0, ...
                                                         'butterorder', 6, ...
                                                         'mipacvarthresh', mipacvarthreshval);
                                                     
%% MVLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);
%% GLM (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'glm',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);    
%% KLMI (no surr)

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'klmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);   
%% INSTMIPAC (surr)
alpha = 0.05;

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'instmipac',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);
%% MVLMI (surr)
alpha = 0.05;

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);
%% GLM (surr)
alpha = 0.05;

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'glm',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);    
%% KLMI (surr)
alpha = 0.05;

[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_singletrial', data_singletrial', s_rate,...
                                                         'methodpac', 'klmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);   
%% Generate 2D data
clear data_pac
max_time      = 2;            % Time of the simulation. Recommended: single trial [6], multiple trials [2]

tlimits      = [-1 max_time];
s_rate        = 200; 

s = randi(maxshift, n_trials,1);

for i=1:n_trials
     plot_flag = i == 1;
     [datatmp,t_outtmp]  = generate_pac_signal(fc,fm,tlimits,'Ac',5,'Am',1,'fs',s_rate,'cpfunc','block','blockamp',1, 'nsegm',nsegm,'plot_flag', plot_flag,'padtime',padtime,'snr',snrval,'m',1);
     datatmp = [datatmp(s(i):end) datatmp(1:s(i)-1)];
     data_pac(1,:,i) = [datatmp(end-ceil(maxshift/2):end) datatmp(1:end-ceil(maxshift/2)-1)]; 
end

%%  MVLMI
% no surr
[pacvalMVLMI, ~, ~, ~, ~, ~,~, pacstructMVLMI] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1);
%%              
% w surr
[pacvalMVLMI, ~, ~, ~, ~, ~,~, pacstructMVLMI] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'mvlmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     0.05 ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1);
%% KLMI 
% no surr
[pacvalKLMI, ~, ~, ~, ~, ~,~, pacstructKLMI] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'klmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'tlimits',   tlimits, ...
                                                         'timefreq',  1);
%%              
% w surr
[pacvalKLMI, ~, ~, ~, ~, ~,~, pacstructKLMI] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'klmi',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     0.05 ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1);
%% GLMmi 
% no surr
[pacvalGLMmi, ~, ~, ~, ~, ~,~, pacstructGLMmi] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'glm',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     alpha ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'tlimits',   tlimits, ...
                                                         'timefreq',  1);
%%              
% w surr
[pacval, ~, ~, ~, ~, ~,~, pacstruct] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'glm',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     0.05 ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1); 
 %%
 %% ERMIPAC
 
 [pacvalERMIPAC, ~, ~, ~, ~, ~,~, pacstructERMIPAC] = eeg_pac(data_pac, data_pac, s_rate,...
                                                         'methodpac', 'ermipac',...
                                                         'freqs',     phaserange ,...
                                                         'alpha',     [] ,...
                                                         'nfreqs1',   nfreqsphase,...
                                                         'nfreqs2',   nfreqsamp,...
                                                         'freqs2',    amprange,...
                                                         'winsize',   s_rate,...
                                                         'nboot',     nsurrogate,...
                                                         'timefreq',  1,...
                                                         'tlimits',   tlimits, ...
                                                         'bonfcorr',  1);
                                                       

                                                     